// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCseawSz5A8i5iS8iSnAH67hw7m74907m4',
    appId: '1:510453225712:web:a9f9784e3ed29155808a35',
    messagingSenderId: '510453225712',
    projectId: 'matoon-fd578',
    authDomain: 'matoon-fd578.firebaseapp.com',
    databaseURL: 'https://matoon-fd578-default-rtdb.firebaseio.com',
    storageBucket: 'matoon-fd578.firebasestorage.app',
    measurementId: 'G-N11SQS8VJ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHOoPhlDrZxn6pXLFo_LDSvhmYX6cjE1E',
    appId: '1:510453225712:android:c18ad359c4cbcef4808a35',
    messagingSenderId: '510453225712',
    projectId: 'matoon-fd578',
    databaseURL: 'https://matoon-fd578-default-rtdb.firebaseio.com',
    storageBucket: 'matoon-fd578.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDb3S4QxO9a0_wNPGSLqezrOZxcT4rpOpY',
    appId: '1:510453225712:ios:6910f3df1c02bd92808a35',
    messagingSenderId: '510453225712',
    projectId: 'matoon-fd578',
    databaseURL: 'https://matoon-fd578-default-rtdb.firebaseio.com',
    storageBucket: 'matoon-fd578.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDb3S4QxO9a0_wNPGSLqezrOZxcT4rpOpY',
    appId: '1:510453225712:ios:6910f3df1c02bd92808a35',
    messagingSenderId: '510453225712',
    projectId: 'matoon-fd578',
    databaseURL: 'https://matoon-fd578-default-rtdb.firebaseio.com',
    storageBucket: 'matoon-fd578.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCseawSz5A8i5iS8iSnAH67hw7m74907m4',
    appId: '1:510453225712:web:f54fa2fc5831d9b3808a35',
    messagingSenderId: '510453225712',
    projectId: 'matoon-fd578',
    authDomain: 'matoon-fd578.firebaseapp.com',
    databaseURL: 'https://matoon-fd578-default-rtdb.firebaseio.com',
    storageBucket: 'matoon-fd578.firebasestorage.app',
    measurementId: 'G-38M98T6QBH',
  );
}
